"use client"
//import "./globals.css"
import { Montserrat } from "next/font/google"
import { ThemeProvider, createTheme } from "@mui/material/styles"
import CssBaseline from "@mui/material/CssBaseline"
import useMediaQuery from "@mui/material/useMediaQuery"
import React from "react"
import { Toaster } from "react-hot-toast"
import Providers from "@/components/Providers"
import SigninButton from "../components/SigninButton"
import Copyright from "@/components/Copyright"

const montserrat = Montserrat({ subsets: ["latin"], display: "swap" })

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	const prefersDarkMode = useMediaQuery("(prefers-color-scheme: dark)")

	const theme = React.useMemo(
		() =>
			createTheme({
				palette: {
					mode: prefersDarkMode ? "dark" : "light",
				},
			}),
		[prefersDarkMode]
	)

	return (
		<html lang="es">
			<body className={montserrat.className}>
				<Providers>
					<ThemeProvider theme={theme}>
						<CssBaseline />
						<div className="w-screen">
							<div className="h-screen">{children}</div>
							<Copyright />
						</div>
						<Toaster />
					</ThemeProvider>
				</Providers>
			</body>
		</html>
	)
}
